// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deci/storage/v2beta1/storage.proto

package storagev2beta1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	v1beta1 "github.com/pardot/deci/proto/deci/storage/v1beta1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Session tracks an authentication throughout it's whole lifecycle. it maps to
// a pardot/oidc session.
type Session struct {
	// details about the initial information we were requested with
	LoginRequest *LoginRequest `protobuf:"bytes,1,opt,name=login_request,json=loginRequest,proto3" json:"login_request,omitempty"`
	// this is the pardot/oidc session we track
	OidcSession *any.Any `protobuf:"bytes,2,opt,name=oidc_session,json=oidcSession,proto3" json:"oidc_session,omitempty"`
	// capture the claims the legacy connector needs if this is nil, the
	// authorization has not yet completed
	Claims *v1beta1.Claims `protobuf:"bytes,3,opt,name=claims,proto3" json:"claims,omitempty"`
	// arbitrary data the connector tracks along with the session. Usually JSON.
	ConnectorData        []byte   `protobuf:"bytes,4,opt,name=connector_data,json=connectorData,proto3" json:"connector_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_51ae16d546309e94, []int{0}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetLoginRequest() *LoginRequest {
	if m != nil {
		return m.LoginRequest
	}
	return nil
}

func (m *Session) GetOidcSession() *any.Any {
	if m != nil {
		return m.OidcSession
	}
	return nil
}

func (m *Session) GetClaims() *v1beta1.Claims {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *Session) GetConnectorData() []byte {
	if m != nil {
		return m.ConnectorData
	}
	return nil
}

// Tracks information about the initial request, so we can pass it to the
// connector on demand
type LoginRequest struct {
	Scopes               []string `protobuf:"bytes,1,rep,name=scopes,proto3" json:"scopes,omitempty"`
	AcrValues            []string `protobuf:"bytes,2,rep,name=acr_values,json=acrValues,proto3" json:"acr_values,omitempty"`
	ClientId             string   `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51ae16d546309e94, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *LoginRequest) GetAcrValues() []string {
	if m != nil {
		return m.AcrValues
	}
	return nil
}

func (m *LoginRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

// maps the subject data dex/deci uses for their ID tokens.
// https://github.com/dexidp/dex/blob/master/server/internal/types.proto
// The proto binary should be Raw UEL encoded to make the subject
// https://github.com/dexidp/dex/blob/master/server/internal/codec.go
type DexSubject struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConnId               string   `protobuf:"bytes,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DexSubject) Reset()         { *m = DexSubject{} }
func (m *DexSubject) String() string { return proto.CompactTextString(m) }
func (*DexSubject) ProtoMessage()    {}
func (*DexSubject) Descriptor() ([]byte, []int) {
	return fileDescriptor_51ae16d546309e94, []int{2}
}

func (m *DexSubject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DexSubject.Unmarshal(m, b)
}
func (m *DexSubject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DexSubject.Marshal(b, m, deterministic)
}
func (m *DexSubject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DexSubject.Merge(m, src)
}
func (m *DexSubject) XXX_Size() int {
	return xxx_messageInfo_DexSubject.Size(m)
}
func (m *DexSubject) XXX_DiscardUnknown() {
	xxx_messageInfo_DexSubject.DiscardUnknown(m)
}

var xxx_messageInfo_DexSubject proto.InternalMessageInfo

func (m *DexSubject) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DexSubject) GetConnId() string {
	if m != nil {
		return m.ConnId
	}
	return ""
}

func init() {
	proto.RegisterType((*Session)(nil), "deci.storage.v2beta1.Session")
	proto.RegisterType((*LoginRequest)(nil), "deci.storage.v2beta1.LoginRequest")
	proto.RegisterType((*DexSubject)(nil), "deci.storage.v2beta1.DexSubject")
}

func init() { proto.RegisterFile("deci/storage/v2beta1/storage.proto", fileDescriptor_51ae16d546309e94) }

var fileDescriptor_51ae16d546309e94 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x5f, 0x4b, 0xeb, 0x30,
	0x00, 0xc5, 0xe9, 0x76, 0xe9, 0x6e, 0xb3, 0xee, 0x3e, 0x84, 0x71, 0xad, 0x53, 0x61, 0x14, 0x84,
	0x3d, 0xa5, 0x6c, 0x0a, 0x3e, 0x08, 0xa2, 0x73, 0x20, 0x03, 0x9f, 0x3a, 0xf0, 0xc1, 0x97, 0x92,
	0x26, 0xb1, 0x46, 0xba, 0x66, 0x26, 0xe9, 0x70, 0xdf, 0xd8, 0x8f, 0x21, 0x49, 0x5a, 0x19, 0x63,
	0x8f, 0xe7, 0x9c, 0x5f, 0x4e, 0x4e, 0xff, 0x80, 0x98, 0x32, 0xc2, 0x13, 0xa5, 0x85, 0xc4, 0x05,
	0x4b, 0xb6, 0xb3, 0x9c, 0x69, 0x3c, 0x6d, 0x35, 0xda, 0x48, 0xa1, 0x05, 0x1c, 0x1a, 0x06, 0xb5,
	0x5e, 0xc3, 0x8c, 0x4e, 0x0b, 0x21, 0x8a, 0x92, 0x25, 0x96, 0xc9, 0xeb, 0xb7, 0x04, 0x57, 0x3b,
	0x77, 0x60, 0x74, 0x50, 0x3a, 0x3d, 0x52, 0x1a, 0x7f, 0x7b, 0xa0, 0xb7, 0x62, 0x4a, 0x71, 0x51,
	0xc1, 0x27, 0x30, 0x28, 0x45, 0xc1, 0xab, 0x4c, 0xb2, 0xcf, 0x9a, 0x29, 0x1d, 0x79, 0x63, 0x6f,
	0xd2, 0x9f, 0xc5, 0xe8, 0xd8, 0xc5, 0xe8, 0xd9, 0xa0, 0xa9, 0x23, 0xd3, 0xb0, 0xdc, 0x53, 0xf0,
	0x06, 0x84, 0x82, 0x53, 0x92, 0x29, 0x57, 0x1c, 0x75, 0x6c, 0xcf, 0x10, 0xb9, 0xa9, 0xa8, 0x9d,
	0x8a, 0x1e, 0xaa, 0x5d, 0xda, 0x37, 0x64, 0xbb, 0xe0, 0x1a, 0xf8, 0xa4, 0xc4, 0x7c, 0xad, 0xa2,
	0xae, 0x3d, 0x72, 0x7e, 0x70, 0xb5, 0x7b, 0x04, 0xf4, 0x68, 0x99, 0xb4, 0x61, 0xe1, 0x25, 0xf8,
	0x47, 0x44, 0x55, 0x31, 0xa2, 0x85, 0xcc, 0x28, 0xd6, 0x38, 0xfa, 0x33, 0xf6, 0x26, 0x61, 0x3a,
	0xf8, 0x75, 0x17, 0x58, 0xe3, 0x38, 0x07, 0xe1, 0xfe, 0x66, 0xf8, 0x1f, 0xf8, 0x8a, 0x88, 0x0d,
	0x53, 0x91, 0x37, 0xee, 0x4e, 0x82, 0xb4, 0x51, 0xf0, 0x02, 0x00, 0x4c, 0x64, 0xb6, 0xc5, 0x65,
	0xcd, 0x54, 0xd4, 0xb1, 0x59, 0x80, 0x89, 0x7c, 0xb1, 0x06, 0x3c, 0x03, 0x01, 0x29, 0x39, 0xab,
	0x74, 0xc6, 0xa9, 0x9d, 0x19, 0xa4, 0x7f, 0x9d, 0xb1, 0xa4, 0xf1, 0x1d, 0x00, 0x0b, 0xf6, 0xb5,
	0xaa, 0xf3, 0x0f, 0x46, 0x34, 0x3c, 0x01, 0xbd, 0x5a, 0x31, 0x69, 0x40, 0xcf, 0x82, 0xbe, 0x91,
	0x4b, 0x6a, 0x02, 0xb3, 0xcd, 0x04, 0x1d, 0x17, 0x18, 0xb9, 0xa4, 0xf3, 0xf9, 0xeb, 0x7d, 0xc1,
	0xf5, 0x7b, 0x9d, 0x23, 0x22, 0xd6, 0xc9, 0x06, 0x4b, 0x2a, 0x74, 0x62, 0x3f, 0xa3, 0x7d, 0x69,
	0xc9, 0xb1, 0xdf, 0xe4, 0xb6, 0xd1, 0x8d, 0xcc, 0x7d, 0x8b, 0x5e, 0xfd, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x06, 0xfe, 0xf2, 0x16, 0x54, 0x02, 0x00, 0x00,
}
